### ISSUE TITLE
Iman kan push men är inte en contributor

### ISSUE THREAD

**Issue by danielptm** [IrinaMix/FinalProjectSpring#3]
Varför kan Iman push men är inte en contributor?

**Comment by danielptm** [comment]
Jag tror att Irina måste kanske lägga till hans email address nånstans. Den här artikeln beskriver situationen. https://help.github.com/articles/i-don-t-see-myself-in-the-repository-contributors-graph/

**Comment by imantahriri** [comment]
Fixed now!
The problem was that I was pushing using another email than what I have in my github account!
If you came across such a problem sometime do like this: 
git config --global user.email "your_git_email_address"
