### ISSUE TITLE
Ta bort findAllByUser(long userId) i WorkItemRepository och WorkItemService

### ISSUE THREAD

**Issue by youthbo** [IrinaMix/FinalProjectSpring#4]
I workItemRepository har vi findAllByUser(long userId) och findAllByUser(User user). Den första funkar inte och vi har findOne(Long id) istället i CrudRepository. Så jag ska ta bort den i workItemRepository och i workItemService.

**Comment by danielptm** [comment]
Okej, jag stänger den här issue för att du har fixat det.
