### ISSUE TITLE
ändras till findAllByStatus(WorkItemStatus status)

### ISSUE THREAD

**Issue by youthbo** [IrinaMix/FinalProjectSpring#5]
findAllByStatus(String status) borde ändras till findAllByStatus(WorkItemStatus status) i WorkItemService.

**Comment by imantahriri** [comment]
Ja håller med. Jag och Mathias diskuterade lite kring detta igår och bestämde fixa viktigare grejer först. Men nu är det bra att fixa det tycker jag.

**Comment by danielptm** [comment]
Jag tycker också det är lite bättre. Jag ska assigna den till dig bo, om du vill inte ta det, assignamig till den. Och sen stäng issue när du är klart.
