### ISSUE TITLE
WorkItems constructor kanske behöver andras

### ISSUE THREAD

**Issue by youthbo** [IrinaMix/FinalProjectSpring#7]
WorkItems constructor har user och issue som parameter. Så man kan assign hur mycket som helst workItem till en user på det här sättet och user kan även vara INACTIVE, issue kan assign till workItem som är inte DONE också. 

Kanske vi behöver ta bort user och issue from WorkItems constructor.

**Comment by IrinaMix** [comment]
Jag tror vi kan ta bort dem från WorkItems constructor.

**Comment by imantahriri** [comment]
det tror jag också för att det blir renare kod annars det inte så svart att fixa det i WorlItemService#create methoden.

**Comment by danielptm** [comment]
Jag tror att du kan ta bort de Bo för att du har testerna till WorkItemService, så då kan ta bort de och göra testerna för att kolla om nåtning har gått sönder.

**Comment by danielptm** [comment]
Och sen stäng issue, om allting fungerar fortfarande.
